[ids]

*

[main]
f23+leftshift+leftmeta = layer(control)
esc = capslock
capslock = overload(capslock, esc)
alt = layer(alt)

[capslock:C]
alt = layer(leader)

[alt:A]
capslock = layer(leader)
h = left
j = down
k = up
l = right
[ = C-left
] = C-right

[leader:C-M-A]
