[ids]

*

[main]
f23+leftshift+leftmeta = layer(control)
esc = capslock
capslock = overload(control, esc)
alt = layer(alt)
j+k = overload(mod, macro(jk))
d+f = overload(mod, macro(df))
tab = overload(move, tab)
k+l = overload(nav, macro(kl))
s+d = overload(nav, macro(sd))

[control:C]

[alt:A]
tab = A-tab

[mod:S-A-M]
s = S-A-M-s
d = S-A-M-d
f = S-A-M-f
j = S-A-M-j
k = S-A-M-k
l = S-A-M-l

[move:C-A-M]
h = left
j = down
k = up
l = right
[ = C-left
] = C-right
space = tab
enter = macro(tab enter)


[nav:S-C-A-M]
s = S-C-A-M-s
d = S-C-A-M-d
f = S-C-A-M-f
j = S-C-A-M-j
k = S-C-A-M-k
l = S-C-A-M-l
