[[mgr.prepend_keymap]]
on = [ "<D-A-O>" ]
run = "tab_create --current"
desc = "Create a new tab with CWD"

[[mgr.prepend_keymap]]
on = [ '<D-A-">' ]
run = "close"
desc = "Close the current tab"

[[mgr.prepend_keymap]]
on = [ "<D-A-J>" ]
run = "tab_switch --relative -1"
desc = "Switch to previous tab"

[[mgr.prepend_keymap]]
on = [ "<D-A-K>" ]
run = "tab_switch --relative 1"
desc = "Switch to previous tab"

[[mgr.prepend_keymap]]
on = [ "<D-A-I>" ]
run = "cd --interactive"
desc = "Jump interactively"

[[mgr.prepend_keymap]]
on = [ "t" ]
run = 'shell --orphan --confirm "kitty"'
desc = "Open with vim"

[[mgr.prepend_keymap]]
on = [ "<S-o>" ]
run = 'shell --orphan --confirm "kitty -e nvim $0"'
desc = "Open with vim"

[[mgr.prepend_keymap]]
on   = "+"
run  = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on   = "-"
run  = "plugin zoom -1"
desc = "Zoom out hovered file"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on  = "y"
run = ["plugin system-clipboard"]

[[mgr.prepend_keymap]]
on = "p"
run = ["shell --block 'cb paste && clear'"]

[[mgr.prepend_keymap]]
on = [ "f" ]
run = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on = [ "g", "l" ]
run = "cd ~/Documents"
desc = "Go ~/Documents"

[[mgr.prepend_keymap]]
on = [ "g", "k" ]
run = "cd ~/Documents/Code"
desc = "Go ~/Documents/Code"

[[mgr.prepend_keymap]]
on = [ "g", "n" ]
run = "cd ~/Documents/College"
desc = "Go ~/Documents/College"

[[mgr.prepend_keymap]]
on = [ "g", "p" ]
run = "cd ~/Music"
desc = "Go ~/Music"

[[mgr.prepend_keymap]]
on = [ "g", "v" ]
run = "cd ~/Videos"
desc = "Go ~/Videos"

[[mgr.prepend_keymap]]
on = [ "g", ";" ]
run = "cd ~/.config"
desc = "Go ~/.config"

[[mgr.prepend_keymap]]
on = [ "g", "t" ]
run = "plugin recycle-bin open"
desc = "Go to Trash"

[[mgr.prepend_keymap]]
on = [ "<Space>", "r", "o" ]
run = "plugin recycle-bin open"
desc = "Open Trash"

[[mgr.prepend_keymap]]
on = [ "<Space>", "r", "e" ]
run = "plugin recycle-bin empty"
desc = "Empty Trash"

[[mgr.prepend_keymap]]
on = [ "<Space>", "r", "d" ]
run = "plugin recycle-bin delete"
desc = "Delete from Trash"

[[mgr.prepend_keymap]]
on = [ "<Space>", "r", "D" ]
run = "plugin recycle-bin emptyDays"
desc = "Empty by days deleted"

[[mgr.prepend_keymap]]
on = [ "<Space>", "r", "r" ]
run = "plugin recycle-bin restore"
desc = "Restore from Trash"

[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "<Space>", "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "<Space>", "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = [ "<Space>", "m", "m" ]
run = "plugin gvfs -- select-then-mount --jump"
desc = "Select device to mount and jump to its mount point"

[[mgr.prepend_keymap]]
on = [ "<Space>", "m", "R" ]
run = "plugin gvfs -- remount-current-cwd-device"
desc = "Remount device under cwd"

[[mgr.prepend_keymap]]
on = [ "<Space>", "m", "u" ]
run = "plugin gvfs -- select-then-unmount --eject"
desc = "Select device then unmount and eject"

[[mgr.prepend_keymap]]
on = [ "<Space>", "m", "a" ]
run = "plugin gvfs -- add-mount"
desc = "Add a GVFS mount URI"

[[mgr.prepend_keymap]]
on = [ "<Space>", "m", "e" ]
run = "plugin gvfs -- edit-mount"
desc = "Edit a GVFS mount URI"

[[mgr.prepend_keymap]]
on = [ "<Space>", "m", "r" ]
run = "plugin gvfs -- remove-mount"
desc = "Remove a GVFS mount URI"

[[mgr.prepend_keymap]]
on = [ "<Space>", "m", "o" ]
run = "plugin gvfs -- jump-to-device"
desc = "Select device then jump to its mount point"

[[mgr.prepend_keymap]]
on = [ "<Space>", "m", "h" ]
run = "plugin gvfs -- jump-back-prev-cwd"
desc = "Jump back to the position before jumped to device"

[[mgr.prepend_keymap]]
on = [ "<C-1>" ]
run = "tab_switch 0"
desc = "Switch to tab 1"

[[mgr.prepend_keymap]]
on = [ "<C-2>" ]
run = "tab_switch 1"
desc = "Switch to tab 2"

[[mgr.prepend_keymap]]
on = [ "<C-3>" ]
run = "tab_switch 2"
desc = "Switch to tab 3"

[[mgr.prepend_keymap]]
on = [ "<C-4>" ]
run = "tab_switch 3"
desc = "Switch to tab 4"

[[mgr.prepend_keymap]]
on = [ "<C-5>" ]
run = "tab_switch 4"
desc = "Switch to tab 5"

[[mgr.prepend_keymap]]
on = [ "<C-6>" ]
run = "tab_switch 5"
desc = "Switch to tab 6"

[[mgr.prepend_keymap]]
on = [ "<C-7>" ]
run = "tab_switch 6"
desc = "Switch to tab 7"

[[mgr.prepend_keymap]]
on = [ "<C-8>" ]
run = "tab_switch 7"
desc = "Switch to tab 8"

[[mgr.prepend_keymap]]
on = [ "<C-9>" ]
run = "tab_switch 8"
desc = "Switch to tab 9"

[[mgr.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions 9"
desc = "Move in relative steps"
