include dracula.conf
enabled_layouts Fat:bias=60, Stack
enable_audio_bell no

cursor_shape              block
shell_integration         no-cursor
inactive_border_color     #404060
background                #1f2329
window_padding_width      2

tab_bar_min_tabs          1
tab_bar_edge              top
tab_bar_style             powerline

inactive_tab_background   #bb8080
inactive_tab_foreground   #2e2430
active_tab_background     #9590e0
active_tab_foreground     #2e2430
tab_bar_background        #343a41
tab_bar_margin_color      #1f2329
tab_bar_margin_width      0.5
tab_bar_margin_height     4.0 1.0
tab_title_template " \uf07b  {title} "

map alt+n layout_action bias 60 50 40
map alt+i next_layout

map alt+o new_tab
map alt+k next_tab
map alt+j previous_tab

map alt+- new_window
map alt+h previous_window
map alt+l next_window
map alt+' close_window

map alt+shift+j move_tab_backward
map alt+shift+k move_tab_forward
map alt+shift+h move_window_backward
map alt+shift+l move_window_forward

map ctrl+backspace send_text all \u0017
map ctrl+delete    send_text all \u001bd
