include dracula.conf
enabled_layouts Fat:bias=60, Stack

cursor_shape              block
shell_integration         no-cursor
inactive_border_color     #404060
background                #1f2329
window_padding_width      2

tab_bar_min_tabs          1
tab_bar_edge              top
tab_bar_style             powerline
inactive_tab_foreground   #fff
inactive_tab_background   #404060
active_tab_foreground     #fff
active_tab_background     #333350
tab_bar_background        #282d35
tab_bar_margin_color      #1f2329
tab_bar_margin_width      0.5
tab_bar_margin_height     4.0 1.0

map ctrl+m layout_action bias 60 50 40
map ctrl+i next_layout

map ctrl+o new_tab
map ctrl+k next_tab
map ctrl+j previous_tab

map ctrl+- new_window
map ctrl+h previous_window
map ctrl+l next_window
map ctrl+' close_window

map ctrl+shift+j move_tab_backward
map ctrl+shift+k move_tab_forward
map ctrl+shift+h move_window_backward
map ctrl+shift+l move_window_forward

map ctrl+backspace send_text all \u0017
map ctrl+delete    send_text all \u001bd
