include dracula.conf
enabled_layouts Fat:bias=70, Stack
cursor_shape block
shell_integration  no-cursor
inactive_border_color #404060
background #1f2329
window_padding_width 2


map ctrl+' layout_action bias 80 50 20
map ctrl+; next_layout

map alt+y neighboring_window left
map alt+o neighboring_window right
map alt+i neighboring_window up
map alt+u neighboring_window down
map alt+; launch --cwd=current
map alt+w close_window

map shift+alt+y move_window left
map shift+alt+u move_window down
map shift+alt+i move_window up
map shift+alt+o move_window right

map ctrl+backspace send_text all \u0017
map ctrl+delete    send_text all \u001bd
