swipe:
  3:
    begin:
      command: xdotool keydown Alt+Tab && xdotool keyup Tab
      interval: 2
    right:
      update:
        command: xdotool key Tab
        interval: 2
    left:
      update:
        command: xdotool key Shift+Tab
        interval: 2
    end:
      command: xdotool keyup Alt
  4:
    left:
      update:
        command: 'xdotool key super+o'
        interval: 3
    right:
      update:
        command: 'xdotool key super+y'
        interval: 3
    up:
      update:
        command: 'xdotool key super+w'
        interval: 3
    down:
      update:
        command: 'xdotool key super+w'
        interval: 3

pinch:
  2:
    in:
      begin:
        command: 'xdotool key super+minus'
      update:
        command: 'xdotool key super+minus'
    out:
      begin:
        command: 'xdotool key super+equal'
      update:
        command: 'xdotool key super+equal'
