swipe:
  3:
    begin:
      command: 'ydotool key 56:1 15:1 15:0'
      interval: 3
    right:
      update:
        command: 'ydotool key 15:1 15:0'
        interval: 3
    left:
      update:
        command: 'ydotool key 42:1 15:1 15:0 42:0'
        interval: 3
    end:
      command: 'ydotool key 56:0'
  4:
    left:
      update:
        command: 'ydotool key 125:1 37:1 37:0 125:0'
        interval: 3
    right:
      update:
        command: 'ydotool key 125:1 36:1 36:0 125:0'
        interval: 3
    up:
      update:
        command: 'ydotool key 125:1 17:1 17:0 125:0'
        interval: 3
    down:
      update:
        command: 'ydotool key 125:1 17:1 17:0 125:0'
        interval: 3
